from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views
from Training_App.views import Message

urlpatterns = [
    path('', views.Home, name='Home'),
    path('Admin_Login/', views.Admin_Login, name='Admin_Login'),
    path('Teacher_Login/', views.Teacher_Login, name='Teacher_Login'),
    path('Teacher_Registration/', views.Teacher_Registration, name='Teacher_Registration'),
    path('Student_Login/', views.Student_Login, name='Student_Login'),
    path('Student_Registration/', views.Student_Registration, name='Student_Registration'),
    path('User_Management/', views.User_Management, name='User_Management'),
    path('Course_Management/', views.Course_Management, name='Course_Management'),
    path('Update_Teacher/', views.Update_Teacher, name='Update_Teacher'),
    path('Delete_Teacher/<int:id>/', views.Delete_Teacher, name='Delete_Teacher'),
    path('Add_Course/', views.Add_Course, name='Add_Course'),
    path('Teacher_Course_Management/', views.Teacher_Course_Management, name='Teacher_Course_Management'),
    path('Add_Lectures/<int:id>/', views.Add_Lectures, name='Add_Lectures'),
    path('Add_Assignments/<int:id>/', views.Add_Assignments, name='Add_Assignments'),
    path('View_Course/', views.View_Course, name='View_Course'),
    path('View_Lectures/<int:id>/', views.View_Lectures, name='View_Lectures'),
    path('Enroll/<int:id>/', views.Enroll, name='Enroll'),
    path('Update_Course/', views.Update_Course, name='Update_Course'),
    path('Update_Lecture/', views.Update_Lecture, name='Update_Lecture'),
    path('Delete_Course/<int:id>/', views.Delete_Course, name='Delete_Course'),
    path('Delete_Lecture/<int:id>/', views.Delete_Lecture, name='Delete_Lecture'),
    path('View_Assignments/<int:id>/', views.View_Assignments, name='View_Assignments'),
    path('Submit_Assignments/<int:id>/', views.Submit_Assignments, name='Submit_Assignments'),
    path('View_Student_Assignments/<int:id>/', views.View_Student_Assignments, name='View_Student_Assignments'),
    path('Update_Remarks/<int:id>/', views.Update_Remarks, name='Update_Remarks'),
    path('Add_Quiz/<int:id>/', views.Add_Quiz, name='Add_Quiz'),
    path('Add_Questions/<int:id>/', views.Add_Questions, name='Add_Questions'),
    path('Delete_Quiz/<int:id>/', views.Delete_Quiz, name='Delete_Quiz'),
    path('Update_Quiz/', views.Update_Quiz, name='Update_Quiz'),
    path('View_Quiz/<int:id>/', views.View_Quiz, name='View_Quiz'),
    path('View_Questions/<int:id>/', views.View_Questions, name='View_Questions'),
    path('Submit_Quiz/', views.Submit_Quiz, name='Submit_Quiz'),
    path('Create_Group/<int:id>/', views.Create_Group, name='Create_Group'),
    path('Add_Group/<int:id>/', views.Add_Group, name='Add_Group'),
    path('Add_Students/<int:student_id>/<int:group_id>/<int:course_id>/', views.Add_Students, name='Add_Students'),
    path('View_Group_Members/<int:group_id>/', views.View_Group_Members, name='View_Group_Members'),
    path('View_Chat/<int:group_id>/', views.View_Chat, name='View_Chat'),
    path('Progress_Tracking/<int:id>/', views.Progress_Tracking, name='Progress_Tracking'),
    path('Progress_Tracking_Teacher/<int:id>/<int:course_id>/', views.Progress_Tracking_Teacher, name='Progress_Tracking_Teacher'),
    path('Student_Progress/<int:id>/', views.Student_Progress, name='Student_Progress'),
    path('View_Group/<int:id>/', views.View_Group, name='View_Group'),
    path('Add_Comment/', views.Add_Comment, name='Add_Comment'),
    path('Show_Monthly_graph/<int:course_id>/', views.Show_Monthly_graph, name='Show_Monthly_graph'),
    path('Feedback/', views.Feedback, name='Feedback'),
    path('Logout/', views.Logout, name='Logout'),
    path('Manage_Category/', views.Manage_Category, name='Manage_Category'),
    path('add_category/', views.add_category, name='add_category'),
    path('add_subcategory/', views.add_subcategory, name='add_subcategory'),
    path('edit_category/<int:id>/', views.edit_category, name='edit_category'),
    path('delete_category/<int:id>/', views.delete_category, name='delete_category'),
    path('edit_subcategory/<int:id>/', views.edit_subcategory, name='edit_subcategory'),
    path('delete_subcategory/<int:id>/', views.delete_subcategory, name='delete_subcategory'),
    path('Manage_Subcategory/<int:id>/', views.Manage_Subcategory, name='Manage_Subcategory'),
    path('get_subcategories/<int:category_id>/', views.get_subcategories, name='get_subcategories'),
    path('teacher_groups/', views.view_teacher_groups, name='teacher_groups'),
    path('teacher_overview/', views.overview_teacher_courses, name='teacher_overview'),
    path('enrollment_report/', views.enrollment_report, name='enrollment_report'),
    path('View_Students/<int:course_id>/<int:group_id>/', views.View_Students, name='View_Students'),

    path('chatbot/', views.chatbot, name='chatbot'),
    path('Message/', Message.as_view(), name='Message'),
    path('manage_ai_article/', views.manage_ai_article, name='manage_ai_article'),
    path('add_ai_article/', views.add_ai_article, name='add_ai_article'),
    path('delete_ai_article/', views.delete_ai_article, name='delete_ai_article'),
    path('update_ai_article/<int:id>/', views.update_ai_article, name='update_ai_article'),
    path('updated_ai_article/', views.updated_ai_article, name='updated_ai_article'),
    path('course_enrollment_report/', views.course_enrollment_report, name='course_enrollment_report'),
    path('student_performance_report/', views.student_performance_report, name='student_performance_report'),
    path('feedback_report/', views.feedback_report, name='feedback_report'),
    path('Analytics_and_Reporting/', views.Analytics_and_Reporting, name='Analytics_and_Reporting'),
    path('Give_Feedback/', views.Give_Feedback, name='Give_Feedback'),
    path('User_Support/', views.User_Support, name='User_Support'),
    path('reply_feedback/<int:feedback_id>/', views.reply_feedback, name='reply_feedback'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
