# Generated by Django 3.2.25 on 2024-08-24 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=None, max_length=100)),
                ('password', models.CharField(default=None, max_length=100)),
            ],
            options={
                'db_table': 'AdminDetails',
            },
        ),
        migrations.CreateModel(
            name='AITrainingArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('introduction', models.TextField(blank=True, max_length=155500, null=True)),
                ('content', models.TextField(blank=True, max_length=155500, null=True)),
                ('example_blog', models.TextField(blank=True, max_length=155500, null=True)),
                ('visuals1', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('visuals2', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('visuals3', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('conclusion', models.TextField(blank=True, max_length=155500, null=True)),
                ('references_sources1', models.TextField(blank=True, max_length=155500, null=True)),
                ('references_sources2', models.TextField(blank=True, max_length=155500, null=True)),
                ('references_sources3', models.TextField(blank=True, max_length=155500, null=True)),
                ('references_sources4', models.TextField(blank=True, max_length=155500, null=True)),
            ],
            options={
                'db_table': 'AITrainingArticle',
            },
        ),
        migrations.CreateModel(
            name='Assignments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_file', models.FileField(upload_to='assignment_files/')),
            ],
            options={
                'db_table': 'Assignments',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, null=True)),
                ('category_description', models.TextField(null=True)),
            ],
            options={
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled Course', max_length=100, null=True)),
                ('description', models.TextField()),
                ('level', models.CharField(default='Beginner', max_length=20)),
                ('enrollment_count', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='Training_App.category')),
            ],
            options={
                'db_table': 'Course',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Training_App.course')),
            ],
            options={
                'db_table': 'Group',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(default=None, max_length=100, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Student',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'Tag',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('address', models.CharField(default=None, max_length=200, null=True)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('birth_date', models.DateField(null=True)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('username', models.CharField(max_length=100, null=True)),
                ('password', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'Teacher',
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='Training_App.course')),
            ],
            options={
                'db_table': 'Title',
            },
        ),
        migrations.CreateModel(
            name='SubmittedQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz', models.CharField(max_length=100)),
                ('score', models.IntegerField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_quizzes', to='Training_App.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_quizzes', to='Training_App.student')),
            ],
            options={
                'db_table': 'SubmittedQuiz',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_name', models.CharField(max_length=100, null=True)),
                ('subcategory_description', models.TextField(null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='Training_App.category')),
            ],
            options={
                'db_table': 'SubCategory',
            },
        ),
        migrations.CreateModel(
            name='StudentAssignments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_file', models.FileField(upload_to='student_assignment_files/')),
                ('student_id', models.CharField(max_length=100)),
                ('remarks', models.CharField(max_length=200, null=True)),
                ('assignment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Training_App.assignments')),
            ],
            options={
                'db_table': 'StudentAssignments',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default=None, max_length=100, null=True)),
                ('option1', models.CharField(default=None, max_length=100, null=True)),
                ('option2', models.CharField(default=None, max_length=100, null=True)),
                ('option3', models.CharField(default=None, max_length=100, null=True)),
                ('option4', models.CharField(default=None, max_length=100, null=True)),
                ('answer', models.CharField(default=None, max_length=100, null=True)),
                ('title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Training_App.title')),
            ],
            options={
                'db_table': 'Questions',
            },
        ),
        migrations.CreateModel(
            name='Lectures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_no', models.IntegerField(blank=True, null=True)),
                ('lecture_name', models.CharField(blank=True, max_length=100, null=True)),
                ('lecture_description', models.TextField()),
                ('video_file', models.FileField(upload_to='lecture_videos/')),
                ('duration', models.CharField(max_length=100)),
                ('add_date', models.DateTimeField(blank=True, null=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Training_App.course')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Training_App.teacher')),
            ],
            options={
                'db_table': 'Lectures',
            },
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Training_App.student')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Training_App.subcategory')),
            ],
            options={
                'db_table': 'Interest',
            },
        ),
        migrations.CreateModel(
            name='Group_Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Training_App.group')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Training_App.student')),
            ],
            options={
                'db_table': 'Group_Member',
            },
        ),
        migrations.CreateModel(
            name='FeedbackData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(default=None, max_length=100, null=True)),
                ('sentiment', models.CharField(default=None, max_length=100, null=True)),
                ('remarks', models.CharField(default=None, max_length=100, null=True)),
                ('admin_reply', models.TextField(blank=True, default='')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FeedbackData', to='Training_App.student')),
            ],
            options={
                'db_table': 'FeedbackData',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(default=None, max_length=100, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Training_App.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Training_App.student')),
            ],
            options={
                'db_table': 'Enrollment',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='Training_App.subcategory'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='Training_App.teacher'),
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default=None, max_length=200, null=True)),
                ('comment', models.CharField(default=None, max_length=200, null=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Training_App.group')),
            ],
            options={
                'db_table': 'Chat',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text='URL friendly version of the title', unique=True)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('views', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Training_App.teacher')),
                ('categories', models.ManyToManyField(blank=True, related_name='blogs', to='Training_App.Category')),
                ('tags', models.ManyToManyField(blank=True, related_name='blogs', to='Training_App.Tag')),
            ],
            options={
                'db_table': 'Blog',
            },
        ),
        migrations.AddField(
            model_name='assignments',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Training_App.course'),
        ),
    ]
